### ISSUE TITLE
Unexpected token error in qewd start

### ISSUE THREAD

**Issue by abykm** [robtweed/qewd#35]
Hi, I am getting the following error while starting QEWD sample application can you please help?

Node version v4.2.6

/home/aby/qewd/node_modules/qewd/lib/worker.js:54
    this.db.use = function(documentName, ...subscripts) {
                                         ^^^
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/aby/qewd/node_modules/qewd/lib/qewd.js:31:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by abykm** [comment]
It will be fixed if I removed this '...' in worker.js, Is there any change in QEWD if I resolved like this?

**Comment by killmenot** [comment]
@abykm QEWD requires Node.js 6+ (7.6+ if you use webServer `koa`)
